### ISSUE TITLE
Fitting replacement EPIC

### ISSUE THREAD

**Issue by AnthonyLim23** [ISISMuon/WiMDAIssues#2]
This looks to be the code doing the actual fit calculation

https://github.com/ISISMuon/WiMDA/blob/main/src/Fitucode.pas

need to identify:

- [ ] What information it passes back to Wimda
- [ ] What information it receives from Wimda
- [ ] Where it is called in Wimda

**Comment by francis-pratt** [comment]
The actual function doing the fit is called fite and it is called in six places (easily found by searching for references to fite once Delphi is installed):

Plot.pas(229):   fitok := fite(nn, fx, fy, fyerr, x2, errpower, parabfit, m, q, qerr, qvar,
Plot.pas(1859):                   fitok := fite(np, fx, fy, fyerr, x2, errpower, diamagfit, m,

Group.pas(1147):   fite(npt, fx, fy, fyerr, x2, errpower, BGfit, m, q, qerr, qvar,
Group.pas(1373):     fite(np, fx, fy, fyerr, x2, errpower, countfit, m, q, qerr, qvar,
Group.pas(2775):     fite(np, fx, fy, fyerr, x2, errpower, countfit, m, q, qerr, qvar,

Analyse.pas(5458):       if fite(n, xx, Y, yerr, x2, errpower, musrfun, m, p, perr, pvar,

From: Anthony ***@***.***>
Sent: Monday, October 16, 2023 9:57 AM
To: ISISMuon/WiMDAIssues ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ISISMuon/WiMDAIssues] Fitting replacement EPIC (Issue #2)


This looks to be the code doing the actual fit calculation

https://github.com/ISISMuon/WiMDA/blob/main/src/Fitucode.pas

need to identify:

  *   [ ] What information it passes back to Wimda
  *   [ ] What information it receives from Wimda
  *   [ ] Where it is called in Wimda

**Comment by AnthonyLim23** [comment]
https://github.com/ISISMuon/WiMDA/blob/main/src/Fitucode.pas#L150

inputs:
```
 N: integer; # number of data points
 var # (variable)
      X # x data
      Y # y data
     ERRY # y errors
     X2: array of double; # x^2 data
 E: double; # weighting factor (used as a power) used in chi^2, always 1
 FUNC: ffun; # fitting function (pointer)
 MU: integer; # total number of fit parameters (includes fixed values) 
 var 
     U, # fit parameters (initial and final values)
     udev: array of double; # fit parameter errors 
 var uvar: array of boolean; # free parameters (order is important is its just a list of bools)
 outch: TStrings; # feedback string (like cout?)
 outstat: statusproc; # string of parameter results, displays the fit status
 var chi2: double # chi squared 
```

returns:
```
 boolean; # fit success 
stdcall; # ?
```
